version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security for simplicity
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data  # Persistent storage for Elasticsearch data
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk-network

  nifi:
    image: apache/nifi:latest
    container_name: devnifi
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
    ports:
      - "8443:8443"
    networks:
      - elk-network

  nifi-registry:
    image: apache/nifi-registry:latest
    container_name: nifi-registry
    ports:
      - "18080:18080"
    networks:
      - elk-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - elk-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - elk-network

  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:latest
    container_name: kafka-rest-proxy
    environment:
    - KAFKA_REST_PROXY_LISTENER_URL=http://0.0.0.0:8082
    - KAFKA_REST_BOOTSTRAP_SERVERS=kafka:9092  # Correct the variable name
    #- KAFKA_REST_PROXY_LISTENER_PORT=8082
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    networks:
      - elk-network


volumes:
  esdata:
    driver: local

networks:
  elk-network:
    driver: bridge
